spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ste
    username: ste
    password: stepass
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
server:
  port: 8080
